version: '3.9'

services:
  flugo-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: abc_valera 
      POSTGRES_PASSWORD: abc_valera 
      POSTGRES_DB: flugo
    ports:
      - "5432:5432"
  
  flugo:
    image: flugo:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://abc_valera:abc_valera@flugo-db:5432/flugo?sslmode=disable
    depends_on:
      - flugo-db
