version: "2"
sql:
  - engine: "postgresql"
    queries: "../queries"
    schema: "../migrations"
    gen:
      go:
        package: "database"
        out: "../../database"
        emit_json_tags: true